#! python


def build(ctx):

    # Illustrate simple use of run_py_script
    ctx(
        features="run_py_script",
        source="schedule_scraper.py",
        target=ctx.path_to(ctx, "DATA", "Boxscores2009.xlsx"),
        target=ctx.path_to(ctx, "DATA", "Boxscores2010.xlsx"),
        target=ctx.path_to(ctx, "DATA", "Boxscores2011.xlsx"),
        target=ctx.path_to(ctx, "DATA", "Boxscores2012.xlsx"),
        target=ctx.path_to(ctx, "DATA", "Boxscores2013.xlsx"),
        target=ctx.path_to(ctx, "DATA", "Boxscores2014.xlsx"),
        target=ctx.path_to(ctx, "DATA", "Boxscores2015.xlsx"),
        target=ctx.path_to(ctx, "DATA", "Boxscores2016.xlsx"),
        target=ctx.path_to(ctx, "DATA", "Boxscores2017.xlsx"),
        target=ctx.path_to(ctx, "DATA", "Boxscores2018.xlsx"),
        name="get_data",
    )
