name: predict_bball
channels:
  - defaults
dependencies:
  - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2020.1.1
  - cairo=1.14.12
  - certifi=2019.11.28
  - defusedxml=0.6.0
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gettext=0.19.8.1
  - glib=2.63.1
  - graphite2=1.3.13
  - graphviz=2.40.1
  - harfbuzz=1.8.8
  - icu=58.2
  - importlib_metadata=1.5.0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.3
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - jdcal=1.4.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - json5=0.9.1
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - jupyterlab=1.2.6
  - jupyterlab_server=1.0.6
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libpng=1.6.37
  - libsodium=1.0.16
  - libtiff=4.1.0
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nb_conda_kernels=2.2.2
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.2
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openpyxl=3.0.3
  - openssl=1.1.1d
  - pandas=0.25.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.6.1
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=19.2.3
  - pixman=0.38.0
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - ptyprocess=0.6.0
  - pygments=2.5.2
  - pyrsistent=0.15.7
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-graphviz=0.8.4
  - pytz=2019.3
  - pyzmq=18.1.1
  - readline=7.0
  - send2trash=1.5.0
  - setuptools=45.2.0
  - six=1.14.0
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - xlrd=1.2.0
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - alabaster==0.7.12
    - appdirs==1.4.3
    - aspy-yaml==1.3.0
    - atomicwrites==1.3.0
    - babel==2.8.0
    - beautifulsoup4==4.7.1
    - cfgv==3.1.0
    - chardet==3.0.4
    - click==7.0
    - coverage==5.0.3
    - cycler==0.10.0
    - distlib==0.3.0
    - docutils==0.16
    - filelock==3.0.12
    - identify==1.4.11
    - idna==2.8
    - imageio==2.8.0
    - imagesize==1.2.0
    - joblib==0.14.1
    - kiwisolver==1.1.0
    - matplotlib==3.1.1
    - more-itertools==8.2.0
    - nbsphinx==0.4.2
    - networkx==2.4
    - nodeenv==1.3.5
    - packaging==20.3
    - pillow==7.0.0
    - pluggy==0.13.1
    - pre-commit==1.18.3
    - py==1.8.1
    - pyparsing==2.4.6
    - pytest==5.2.0
    - pytest-cov==2.7.1
    - pytest-pythonpath==0.7.3
    - pywavelets==1.1.1
    - pyyaml==5.3
    - requests==2.22.0
    - scikit-image==0.15.0
    - scikit-learn==0.21.3
    - scipy==1.4.1
    - snowballstemmer==2.0.0
    - soupsieve==2.0
    - sphinx==2.4.4
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - toml==0.10.0
    - urllib3==1.24.3
    - virtualenv==20.0.8
