name: predict_bball
channels:
  - defaults

dependencies:
  - ipykernel=5.1.3
  - jupyterlab=1.2.6
  - numpy
  - pandas=0.25.1
  - pip=19.2.3
  - python=3.7
  - python-graphviz=0.8
  - nb_conda_kernels=2.2.2

  - pip:
    - beautifulsoup4==4.7.1
    - click==7.0
    - pre-commit==1.18.3
    - matplotlib==3.1.1
    - nbsphinx==0.4.2
    - pytest==5.2.0
    - pytest-cov==2.7.1
    - pytest-pythonpath==0.7.3
    - requests==2.22.0
    - urllib3==1.24.3
